import 'package:flutter/material.dart';
import 'package:flutter_map/flutter_map.dart';
import 'package:flutter_map_vector_tiles/flutter_map_vector_tiles.dart' as vt;
import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../../core/constants/app_config.dart';

/// The map underneath the pins, drawn in BonnetCheck's own colours.
///
/// **Vector tiles rather than pictures.** The map used to be raster tiles from
/// `tile.openstreetmap.org`: flat images, someone else's palette, text baked in
/// at one size, and — the part that mattered — a volunteer-funded server whose
/// usage policy is written for light use, not for an app being handed out.
/// Vector tiles arrive as geometry and are painted here, which is what makes a
/// house style possible at all.
///
/// The two styles are generated by `tool/gen_map_style.py` from OpenFreeMap's
/// Positron and recoloured to `AppColors`. Positron is the base because it was
/// drawn to sit *under* data; a basemap with opinions swallows the pins that
/// are the entire point of these screens.
///
/// **OpenFreeMap needs no key**, which is why it was chosen over MapTiler or
/// Stadia. A key in a Flutter web build is a key published to everyone who
/// opens the site, and rotating it means shipping a release.
class BasemapLayer extends ConsumerWidget {
  const BasemapLayer({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final brightness = Theme.of(context).brightness;
    final style = ref.watch(mapStyleProvider(brightness));

    return style.when(
      data: (s) => vt.VectorTileLayer(
        theme: s.theme,
        tileProviders: s.providers,
        rasterSources: s.rasterSources,
        sprites: s.sprites,
      ),
      // Both of these fall back to the old raster tiles rather than showing a
      // grey rectangle. A map that is the wrong colour for two seconds is a
      // smaller failure than a map that is not there, and after a whole day
      // lost to a screen that rendered blank in release, falling back visibly
      // is the habit worth keeping.
      loading: () => const _RasterFallback(),
      error: (_, __) => const _RasterFallback(),
    );
  }
}

/// Reads and caches one style per theme.
///
/// Keyed by [Brightness] so switching theme swaps the whole basemap without
/// re-reading the style that is already in memory. `keepAlive` because a style
/// is ~20KB of parsed layer rules and neither file ever changes at runtime.
final mapStyleProvider =
    FutureProvider.family<vt.Style, Brightness>((ref, brightness) async {
  ref.keepAlive();
  final name = brightness == Brightness.dark ? 'dark' : 'light';
  return vt.StyleReader(
    uri: 'asset://assets/map/bonnetcheck-$name.json',
    // Named, as OpenFreeMap's policy asks, and carrying the version actually
    // running rather than a number frozen at whatever it was when this line
    // was written.
    headers: {
      'User-Agent':
          'BonnetCheck/${AppConfig.appVersion} (+https://bonnetcheck.web.app)',
    },
  ).read();
});

/// The previous basemap, kept for the seconds before the style is parsed and
/// for the case where it cannot be.
class _RasterFallback extends StatelessWidget {
  const _RasterFallback();

  @override
  Widget build(BuildContext context) => TileLayer(
        urlTemplate: 'https://tile.openstreetmap.org/{z}/{x}/{y}.png',
        userAgentPackageName: 'il.autoproof.autoproof',
        tileProvider: NetworkTileProvider(
          // NOT const: flutter_map writes its own User-Agent into this map,
          // and a const map is unmodifiable. That threw during build and took
          // both map screens down for two days. See map_attribution.dart.
          headers: {
            'User-Agent':
                'BonnetCheck/${AppConfig.appVersion} (+https://bonnetcheck.web.app)',
          },
        ),
      );
}
