// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKQTCzMEh2eCXq_iW7dAm1vvbOVUkQsAY',
    appId: '1:424043770826:web:e9c1995112bf1c0aae5533',
    messagingSenderId: '424043770826',
    projectId: 'autoproof-8d827',
    authDomain: 'autoproof-8d827.firebaseapp.com',
    storageBucket: 'autoproof-8d827.firebasestorage.app',
    measurementId: 'G-RC1YMEXY1Y',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqXuPgkP6RKO_uUJHyCy_0vtwWqfcp-w4',
    appId: '1:424043770826:ios:47d76ca308c225ebae5533',
    messagingSenderId: '424043770826',
    projectId: 'autoproof-8d827',
    storageBucket: 'autoproof-8d827.firebasestorage.app',
    iosBundleId: 'il.autoproof.autoproof',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKQTCzMEh2eCXq_iW7dAm1vvbOVUkQsAY',
    appId: '1:424043770826:web:8a37c297656410bcae5533',
    messagingSenderId: '424043770826',
    projectId: 'autoproof-8d827',
    authDomain: 'autoproof-8d827.firebaseapp.com',
    storageBucket: 'autoproof-8d827.firebasestorage.app',
    measurementId: 'G-NKEL444CD3',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqXuPgkP6RKO_uUJHyCy_0vtwWqfcp-w4',
    appId: '1:424043770826:ios:47d76ca308c225ebae5533',
    messagingSenderId: '424043770826',
    projectId: 'autoproof-8d827',
    storageBucket: 'autoproof-8d827.firebasestorage.app',
    iosBundleId: 'il.autoproof.autoproof',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6PWMaHZu8X8TGpi-3lwfe7a4TcNOl0co',
    appId: '1:424043770826:android:2423b7e09e8f3290ae5533',
    messagingSenderId: '424043770826',
    projectId: 'autoproof-8d827',
    storageBucket: 'autoproof-8d827.firebasestorage.app',
  );
}
